import { Link } from "@tanstack/react-router";
import { Pencil, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { formatCurrency, formatDate } from "@/lib/subscriptions";
import { ReminderBadge } from "@/components/AppShell";

export function SubscriptionCard({ subscription, onDelete }) {
  const initials = subscription.name.slice(0, 1).toUpperCase();
  return <article className="rounded-xl border border-border bg-surface p-4 transition hover:border-primary/40"><div className="flex items-start gap-3"><div className="grid size-11 shrink-0 place-items-center rounded-lg bg-primary/15 font-display text-xl text-primary ring-1 ring-primary/25">{initials}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="truncate font-medium">{subscription.name}</h2><ReminderBadge subscription={subscription} /></div><p className="mt-1 text-xs text-muted-foreground">{subscription.category} · {subscription.billingCycle.toLowerCase()}</p></div><div className="text-right"><div className="font-display text-2xl">{subscription.currency}{Number(subscription.price).toLocaleString("en-IN")}</div><div className="text-[11px] text-muted-foreground">per {subscription.billingCycle.toLowerCase().replace("ly", "")}</div></div></div><div className="mt-4 grid gap-2 border-t border-border pt-3 text-xs text-muted-foreground sm:grid-cols-2"><div><span className="text-muted-foreground/70">Next renewal</span><div className="mt-1 text-foreground">{formatDate(subscription.nextRenewalDate)}</div></div><div><span className="text-muted-foreground/70">Trial status</span><div className="mt-1 text-foreground">{subscription.isTrial ? `Ends ${formatDate(subscription.trialEndDate)}` : "Not a trial"}</div></div></div>{subscription.notes && <p className="mt-3 rounded-md bg-surface-2/50 px-3 py-2 text-xs text-muted-foreground">{subscription.notes}</p>}<div className="mt-4 flex justify-end gap-2"><Button asChild variant="ghost" size="sm"><Link to="/add" search={{ edit: subscription.id }}><Pencil /> Edit</Link></Button><Button variant="ghost" size="sm" className="text-critical hover:bg-critical/10 hover:text-critical" onClick={() => onDelete(subscription)}><Trash2 /> Delete</Button></div></article>;
}
